# @package optimizer

name: "AdamW"
parameters:
  lr: 0.0003
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.0001
  amsgrad : True

max_norm: 0.0
grad_penalty: 0.0
batch_replay: False

use_lookahead: False
lookahead_k: 5
lookahead_alpha: 0.5

use_SAM: False
SAM_rho: 0.5

