# @package optimizer

name: "SGDP"
parameters:
  lr: 0.001
  momentum: 0.9
  dampening: 0
  weight_decay: 0.00001
  nesterov: True
  delta: 0.1
  wd_ratio: 0.1

max_norm: 0.0
grad_penalty: 0.0
batch_replay: False

use_lookahead: False
lookahead_k: 5
lookahead_alpha: 0.5

use_SAM: False
SAM_rho: 0.5
