# @package optimizer

name: "Yogi"
parameters:
  lr: 0.01
  betas: 
      - 0.9
      - 0.999
  eps: 0.001
  initial_accumulator: 0.000001
  weight_decay: 0.001

max_norm: 0.0
grad_penalty: 0.0
batch_replay: False

use_lookahead: False
lookahead_k: 5
lookahead_alpha: 0.5

use_SAM: False
SAM_rho: 0.5
