model: "VGG('VGG19')"
dataset: "CIFAR-10"
half: False
mixpo: False
load_model: ""
lr: 0.01
wd: 0.0
momentum: 0.0
nesterov: False
epoch: 200
train_batch_size: 128
test_batch_size: 512
train_subset:
initialization: 0
initialization_batch_norm: False
save_model: False
save_interval: 5
save_dir: "checkpoints"
lr_milestones: [30, 60, 90, 120,150]
use_reduce_lr: False
reduce_lr_patience: 20
reduce_lr_delta: 0.02
reduce_lr_min_lr: 0.0005
lr_gamma: 0.5
es_patience: 10000
num_workers_train: 4
num_workers_test: 2
all_metrics: False
cuda: True
cuda_device: 0
seed:
progress_bar: False