# @package _global_

half: True
grad_scaler: True
device: 'cuda:0'
seed: 2525
progress_bar: True

save_model: True
save_interval: 10

epochs: 300
val_every: 1
es_patience: 100000
es_metric: 'Train/Accuracy'
scheduler_metric: 'Train/Accuracy'
optimized_metric: "Val/Accuracy"