# @package metrics

Accuracy:
  parameters:
  aggregator: 'mean'
  levels: ['epoch']
  higher_is_better: true

crossentropyloss:
  parameters:
  aggregator: 'mean'
  levels: ['batch', 'epoch']
  higher_is_better: False