# @package transformations

ImageRandomResizedCrop:
  size: 224
  scale: [0.08, 1.0]
  apply_to: 'input'


ImageRandomHorizontalFlip:
  apply_to: 'input'

ImageToTensor:
  apply_to: 'input'

ImageColorJitter:
  brightness: 0.4
  contrast: 0.4
  saturation: 0.4
  apply_to: 'input'


ImageLightingNoise:
  alphastd: 0.1
  eigval: [0.2175, 0.0188, 0.0045]
  eigvec: [
    [-0.5675, 0.7192, 0.4009],
    [-0.5808, -0.0045, -0.8140],
    [-0.5836, -0.6948, 0.4203]
  ]
  apply_to: 'input'


ImageNormalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  apply_to: 'input'


OneHot:
  num_classes: 1000
  apply_to: 'target'
  
val:
  data: [
    {
      'name':"ImageResize",
      'parameters':{
        'size': 256
      }
    },
    {
      'name':"ImageCenterCrop",
      'parameters':{
        'size': 224
      }
    },
    {
      'name':"ImageToTensor",
      'parameters':{
      }
    },
    {
      'name':"ImageNormalize",
      'parameters':{
        'mean': [0.485, 0.456, 0.406],
        'std': [0.229, 0.224, 0.225]
      }
    },
  ]
  target: [
    {
       'name': "OneHot",
       'parameters':
       {
         'num_classes': 1000
       }
     }
  ]