defaults:
  - common: default
  - dataset/train@train_dataset: cifar10
  - dataset/val@val_dataset: cifar10
  - optional hyperparameters: 
  - initializer: default
  - loss: crossentropyloss
  - metrics@train_metrics: [acc_ce] 
  - metrics@val_metrics: [acc_ce] 
  - metrics@solver_metrics: [solver] 
  - model: PreResNet56
  - optimizer: radam 
  - scheduler: milestones
  - override hydra/sweeper: basic   # nevergrad | basic
  - override hydra/launcher: basic

aux_save_dir: 'baseline'
storage_dir: "${oc.env:TENSOR_RELOADED_DATADIR}"
save_dir: "${train_dataset.name}/${model.name}/${aux_save_dir}/${seed}"

load_model: ""

infer_only: False